# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet.proto',
  package='protofile',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpacket.proto\x12\tprotofile\"\x7f\n\x06Packet\x12-\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1c.protofile.EnumPacketCommand\x12\x12\n\nserialized\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63onnectionid\x18\x03 \x01(\x0c\x12\x10\n\x08gametype\x18\x04 \x01(\r\x12\n\n\x02ip\x18\x05 \x01(\t\")\n\x07LogInfo\x12\x0e\n\x06server\x18\x01 \x01(\x0c\x12\x0e\n\x06reason\x18\x02 \x01(\x0c\"\x0b\n\tLoginInfo*T\n\x11\x45numPacketCommand\x12\x10\n\x0cLOGINREQUEST\x10\x00\x12\x11\n\rLOGINRESPONSE\x10\x01\x12\r\n\tGAMELOGIC\x10\x02\x12\x0b\n\x07LOGINFO\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ENUMPACKETCOMMAND = _descriptor.EnumDescriptor(
  name='EnumPacketCommand',
  full_name='protofile.EnumPacketCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOGINREQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGINRESPONSE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAMELOGIC', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGINFO', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=212,
  serialized_end=296,
)
_sym_db.RegisterEnumDescriptor(_ENUMPACKETCOMMAND)

EnumPacketCommand = enum_type_wrapper.EnumTypeWrapper(_ENUMPACKETCOMMAND)
LOGINREQUEST = 0
LOGINRESPONSE = 1
GAMELOGIC = 2
LOGINFO = 3



_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='protofile.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='protofile.Packet.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serialized', full_name='protofile.Packet.serialized', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectionid', full_name='protofile.Packet.connectionid', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gametype', full_name='protofile.Packet.gametype', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='protofile.Packet.ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=154,
)


_LOGINFO = _descriptor.Descriptor(
  name='LogInfo',
  full_name='protofile.LogInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='protofile.LogInfo.server', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='protofile.LogInfo.reason', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=197,
)


_LOGININFO = _descriptor.Descriptor(
  name='LoginInfo',
  full_name='protofile.LoginInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=210,
)

_PACKET.fields_by_name['command'].enum_type = _ENUMPACKETCOMMAND
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['LogInfo'] = _LOGINFO
DESCRIPTOR.message_types_by_name['LoginInfo'] = _LOGININFO
DESCRIPTOR.enum_types_by_name['EnumPacketCommand'] = _ENUMPACKETCOMMAND

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:protofile.Packet)
  ))
_sym_db.RegisterMessage(Packet)

LogInfo = _reflection.GeneratedProtocolMessageType('LogInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOGINFO,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:protofile.LogInfo)
  ))
_sym_db.RegisterMessage(LogInfo)

LoginInfo = _reflection.GeneratedProtocolMessageType('LoginInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOGININFO,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:protofile.LoginInfo)
  ))
_sym_db.RegisterMessage(LoginInfo)


# @@protoc_insertion_point(module_scope)
